<?php

declare(strict_types=1);

namespace AbterPhp\Contact\Constant;

class Env
{
    const DEFAULT_SENDER_EMAIL    = 'DEFAULT_SENDER_EMAIL';
    const DEFAULT_SENDER_NAME     = 'DEFAULT_SENDER_NAME';
    const DEFAULT_RECIPIENT_EMAIL = 'DEFAULT_RECIPIENT_EMAIL';
    const DEFAULT_RECIPIENT_NAME  = 'DEFAULT_RECIPIENT_NAME';

    const DEFAULT_SUCCESS_PAGE = 'DEFAULT_SUCCESS_PAGE';
    const DEFAULT_ERROR_PAGE   = 'DEFAULT_ERROR_PAGE';

    const CONTACT_TEXT_MAX_LENGTH = 'CONTACT_TEXT_MAX_LENGTH';
}
